version: "3"
services:
  angular-app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
    ports:
      - 4100:4200
    volumes:
      - /app/node_modules
      - .:/app
